/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package plagiasi;

import java.awt.Dimension;
import java.awt.ScrollPane;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.math.BigInteger;
import java.sql.*;
import java.text.DecimalFormat;
import java.util.TreeSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.table.*;
import java.util.ResourceBundle;
import javax.swing.JScrollPane;

/**
 *
 * @author idrus
 */
public class MainFrame extends javax.swing.JFrame {

    private static Connection koneksi;
    public ResultSet rs;
    public PreparedStatement pst;
    
    
    
    public void lebarKolom(){

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "No", "Nama File 1", "Nama File 2", "k-gram", "bil.prima", "window", "algoritma", "similarity", "waktu", "tgl_tes"
                }
        ));
        
        TableColumn column;
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        column = jTable1.getColumnModel().getColumn(0);
        column.setPreferredWidth(50);
        column = jTable1.getColumnModel().getColumn(1);
        column.setPreferredWidth(200);
        column = jTable1.getColumnModel().getColumn(2);
        column.setPreferredWidth(200);
        column = jTable1.getColumnModel().getColumn(3);
        column.setPreferredWidth(50);
        column = jTable1.getColumnModel().getColumn(4);
        column.setPreferredWidth(75);
        column = jTable1.getColumnModel().getColumn(5);
        column.setPreferredWidth(75);
        column = jTable1.getColumnModel().getColumn(6);
        column.setPreferredWidth(100);
        column = jTable1.getColumnModel().getColumn(7);
        column.setPreferredWidth(75);
        column = jTable1.getColumnModel().getColumn(8);
        column.setPreferredWidth(50);
        column = jTable1.getColumnModel().getColumn(9);
        column.setPreferredWidth(100);
        
    }

    private static Connection buka_koneksi() {
        if (koneksi == null) {
            try {
                String url = "jdbc:mysql://localhost:3306/perbandingan";
                String user = "root";
                String password = "";

                DriverManager.registerDriver(new com.mysql.jdbc.Driver());
                koneksi = DriverManager.getConnection(url, user, password);
            } catch (SQLException t) {
                System.out.println("Error membuat koneksi");
            }
        }
        return koneksi;
    }

    String simpandok1, simpandok2;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        lebarKolom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonHome = new javax.swing.JButton();
        jButtonCek = new javax.swing.JButton();
        jButtonHistory = new javax.swing.JButton();
        jButtonHelp = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanelHome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelCek = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        ButtonHitung = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<String>();
        jPanelHistory = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelHelp = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jPanel1.setBackground(new java.awt.Color(45, 52, 181));

        jPanel2.setBackground(new java.awt.Color(147, 141, 240));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        jLabel1.setFont(new java.awt.Font("Khmer OS", 0, 24)); // NOI18N
        jLabel1.setText("APLIKASI CEK PLAGIASI DOKUMEN");

        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plagiasi/Home-kecil.png"))); // NOI18N
        jButtonHome.setText("HOME");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jButtonCek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plagiasi/App-document-find-kecil.png"))); // NOI18N
        jButtonCek.setText("CEK PLAGIASI");
        jButtonCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCekActionPerformed(evt);
            }
        });

        jButtonHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plagiasi/Folder-URL-History-kecil.png"))); // NOI18N
        jButtonHistory.setText("HISTORY");
        jButtonHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHistoryActionPerformed(evt);
            }
        });

        jButtonHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plagiasi/Button-Help-kecil.png"))); // NOI18N
        jButtonHelp.setText("HELP");
        jButtonHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHelpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonHome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCek)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonHelp)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHome)
                    .addComponent(jButtonCek)
                    .addComponent(jButtonHistory)
                    .addComponent(jButtonHelp)))
        );

        jPanel3.setBackground(new java.awt.Color(157, 220, 210));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jPanel3.setLayout(new java.awt.CardLayout());

        jLabel2.setText("Plagiasi adalah ");

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        jPanel3.add(jPanelHome, "card2");

        jLabel3.setText("Masukkan dokumen 1 : ");

        jLabel4.setText("Masukkan dokumen 2 :");

        jTextPane1.setAutoscrolls(false);
        jScrollPane1.setViewportView(jTextPane1);

        jButton5.setText("Browse");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jTextPane2);

        jButton6.setText("Browse");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel5.setText("Masukkan nilai k-gram = ");

        jScrollPane3.setViewportView(jTextPane3);

        jLabel6.setText("Masukkan bilangan prima = ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "5", "7", "11", "13", "17", "19", "23", "29", "31" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Masukkan ukuran window = ");

        jScrollPane4.setViewportView(jTextPane4);

        ButtonHitung.setText("Hitung");
        ButtonHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHitungActionPerformed(evt);
            }
        });

        jLabel9.setText("Algoritma yang dipakai =  ");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Winnowing", "Biword Winnowing" }));

        javax.swing.GroupLayout jPanelCekLayout = new javax.swing.GroupLayout(jPanelCek);
        jPanelCek.setLayout(jPanelCekLayout);
        jPanelCekLayout.setHorizontalGroup(
            jPanelCekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCekLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCekLayout.createSequentialGroup()
                        .addGroup(jPanelCekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(2, 2, 2)
                        .addGroup(jPanelCekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addComponent(jButton6)))
                    .addGroup(jPanelCekLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCekLayout.createSequentialGroup()
                        .addGroup(jPanelCekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(2, 2, 2)
                        .addGroup(jPanelCekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonHitung)))
                    .addGroup(jPanelCekLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        jPanelCekLayout.setVerticalGroup(
            jPanelCekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCekLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(ButtonHitung)
                .addGap(21, 21, 21))
        );

        jPanel3.add(jPanelCek, "card3");

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        //jTable1.setMaximumSize(new java.awt.Dimension(2147483647, 208));        
		//jTable1.setPreferredSize(new java.awt.Dimension(5000, 5000));
        jScrollPane5.setViewportView(jTable1);

        javax.swing.GroupLayout jPanelHistoryLayout = new javax.swing.GroupLayout(jPanelHistory);
        jPanelHistory.setLayout(jPanelHistoryLayout);
        jPanelHistoryLayout.setHorizontalGroup(
            jPanelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHistoryLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 99, Short.MAX_VALUE))
        );
        jPanelHistoryLayout.setVerticalGroup(
            jPanelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHistoryLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 175, Short.MAX_VALUE))
        );

        jPanel3.add(jPanelHistory, "card2");

        jLabel8.setText("petunjuk penggunaan aplikasi");

        javax.swing.GroupLayout jPanelHelpLayout = new javax.swing.GroupLayout(jPanelHelp);
        jPanelHelp.setLayout(jPanelHelpLayout);
        jPanelHelpLayout.setHorizontalGroup(
            jPanelHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHelpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHelpLayout.setVerticalGroup(
            jPanelHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHelpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        jPanel3.add(jPanelHelp, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();

            PDFManager pdfManager = new PDFManager();
            pdfManager.setFilePath(file.getAbsolutePath());
            jTextPane1.setText(file.getAbsolutePath());

            try {
                simpandok1 = pdfManager.ToText();
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:

        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(jPanelHome);
        jPanel3.repaint();
        jPanel3.revalidate();

    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCekActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(jPanelCek);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_jButtonCekActionPerformed

    private void jButtonHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHistoryActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(jPanelHistory);
        jPanel3.repaint();
        jPanel3.revalidate();
        
        
        try {
            buka_koneksi();
            String sql = "SELECT * FROM hasil;";
            pst = koneksi.prepareStatement(sql);
            //System.out.println("upil");
            rs = pst.executeQuery();
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            for (int i = 0; i < dtm.getRowCount(); i++) {
                dtm.removeRow(i);
                i = i - 1;
            }
            dtm.setRowCount(0);
            String[] data = new String[11];
            int i = 1;
            jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            //jTable1.setSize(1000, 500);
            while (rs.next()) {
                data[0] = rs.getString("id_file");
                data[1] = rs.getString("nama_file1");
                data[2] = rs.getString("nama_file2");
                data[3] = rs.getString("k_gram");
                data[4] = rs.getString("bil_prima");
                data[5] = rs.getString("window");
                data[6] = rs.getString("algoritma");
                data[7] = rs.getString("similarity");
                data[8] = rs.getString("waktu");
                data[9] = rs.getString("tgl_tes");
                dtm.addRow(data);
                i++;
                //System.out.println("data " + data[9]);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jButtonHistoryActionPerformed

    private void jButtonHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHelpActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(jPanelHelp);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_jButtonHelpActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();

            PDFManager pdfManager = new PDFManager();
            pdfManager.setFilePath(file.getAbsolutePath());
            jTextPane2.setText(file.getAbsolutePath());

            try {
                simpandok2 = pdfManager.ToText();
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void ButtonHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHitungActionPerformed
        // TODO add your handling code here:
        Date tgl = new Date();
        SimpleDateFormat a = new SimpleDateFormat("yyyy-MM-dd");
        System.out.println(a.format(tgl));

        DecimalFormat df = new DecimalFormat("#.##");

        BigInteger sim2, jum2;
        double fs1, fs2;
        int sim1, jum1;
        long start1, start2, finish1, fininsh2, akhir1, akhir2;

        int hash = Integer.parseInt(jTextPane3.getText());
        int basis = Integer.parseInt(jComboBox1.getSelectedItem().toString());
        int window = Integer.parseInt(jTextPane4.getText());

        if (jComboBox2.getSelectedItem().toString().equals("Winnowing")) {

            start1 = System.nanoTime();
            ProsesSatu doc1 = new ProsesSatu();
            ProsesSatu doc2 = new ProsesSatu();

            doc1.hashValue = hash;
            doc1.basisValue = basis;
            doc1.windowValue = window;
            doc2.hashValue = hash;
            doc2.basisValue = basis;
            doc2.windowValue = window;

            try {
                doc1.mainframe(simpandok1);
                doc2.mainframe(simpandok2);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            sim1 = doCompare1(doc1.fingerprint, doc2.fingerprint);
            jum1 = union1(doc1.fingerprint, doc2.fingerprint, doc1.hitung(doc1.fingerprint), doc2.hitung(doc2.fingerprint));
            fs1 = (double) sim1 / (double) jum1;
            fs1 *= 100;
            String similarity1 = df.format(fs1);
            System.out.println(" " + sim1);
            System.out.println(" " + jum1);
            System.out.println(similarity1 + "%");
            finish1 = System.nanoTime();
            akhir1 = finish1 - start1;
            String waktu1 = df.format((double) akhir1 / 1000000000);
            System.out.println("waktu komputasi = " + waktu1);

            Connection c = buka_koneksi();
            if (ButtonHitung.equals(this.ButtonHitung)) {
                String sqlkode = "insert into hasil values(?,?,?,?,?,?,?,?,?,?)";
                try { //jalankan query tersebut

                    PreparedStatement p2 = (PreparedStatement) c.prepareStatement(sqlkode);

                    p2.setInt(1, 0);
                    p2.setString(2, jTextPane1.getText());
                    p2.setString(3, jTextPane2.getText());
                    p2.setString(4, jTextPane3.getText());
                    p2.setString(5, jComboBox1.getSelectedItem().toString());
                    p2.setString(6, jTextPane4.getText());
                    p2.setString(7, jComboBox2.getSelectedItem().toString());
                    p2.setString(8, similarity1);
                    p2.setString(9, waktu1);
                    p2.setString(10, a.format(tgl));

                    p2.executeUpdate();
                    p2.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Terjadi kesalahan " + ex.getMessage());
                }
            }
            ResourceBundle.clearCache();

        } else {

            start2 = System.nanoTime();
            ProsesDua dok1 = new ProsesDua();
            ProsesDua dok2 = new ProsesDua();

            dok1.basisValue = basis;
            dok1.windowValue = window;
            dok2.basisValue = basis;
            dok2.windowValue = window;

            try {

                dok1.mainframe(simpandok1);
                dok2.mainframe(simpandok2);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

            sim2 = new BigInteger("" + doCompare(dok1.fingerprint, dok2.fingerprint));
            jum2 = new BigInteger("" + union(dok1.fingerprint, dok2.fingerprint, dok1.hitung(dok1.fingerprint), dok2.hitung(dok2.fingerprint)));
            fs2 = Double.parseDouble(sim2.toString()) / Double.parseDouble(jum2.toString());
            fs2 *= 100;
            String similarity2 = df.format(fs2);
            System.out.println(" " + sim2);
            System.out.println(" " + jum2);
            System.out.println(similarity2 + "%");
            fininsh2 = System.nanoTime();
            akhir2 = fininsh2 - start2;
            String waktu2 = df.format((double) akhir2 / 1000000000);
            System.out.println("waktu komputasi = " + waktu2);

            Connection c = buka_koneksi();
            if (ButtonHitung.equals(this.ButtonHitung)) {
                String sqlkode = "insert into hasil values(?,?,?,?,?,?,?,?,?,?)";
                try { //jalankan query tersebut

                    PreparedStatement p2 = (PreparedStatement) c.prepareStatement(sqlkode);

                    p2.setInt(1, 0);
                    p2.setString(2, jTextPane1.getText());
                    p2.setString(3, jTextPane2.getText());
                    p2.setInt(4, 0);
                    p2.setString(5, jComboBox1.getSelectedItem().toString());
                    p2.setString(6, jTextPane4.getText());
                    p2.setString(7, jComboBox2.getSelectedItem().toString());
                    p2.setString(8, similarity2);
                    p2.setString(9, waktu2);
                    p2.setString(10, a.format(tgl));

                    p2.executeUpdate();
                    p2.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Terjadi kesalahan " + ex.getMessage());
                }
            }
            ResourceBundle.clearCache();
        }
    }//GEN-LAST:event_ButtonHitungActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        //NILAI BILANGAN PRIMA
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });

    }

    static int union(BigInteger[] a, BigInteger[] b, int asize, int bsize) {
//        System.out.println("a = "+a.length);
//        System.out.println("b = "+b.length);
//        System.out.println("asize = "+asize);
//        System.out.println("bsize = "+bsize);
        TreeSet<String> t = new TreeSet<String>();
        //ProsesSatu pc = new ProsesSatu();
        for (int i = 0; i < asize; i++) {
            t.add(a[i].toString());
        }
        for (int i = 0; i < bsize; i++) {
            t.add(b[i].toString());
        }
        return t.size();
    }

    static int doCompare(BigInteger[] a, BigInteger[] b) {
        int i = 0;
        int j = 0;
        int score = 0;
        while (a[i] != null) {
            j = 0;
            while (b[j] != null) {
                if (a[i].toString().equals(b[j].toString())) {
                    score += 1;
                    //System.out.println(a[j]);
                }
                j++;

            }
            i++;
        }
        return score;
    }

    //yang proses satu nih pake integer aja
    static int union1(long[] a, long[] b, int asize, int bsize) {
//        System.out.println("a = "+a.length);
//        System.out.println("b = "+b.length);
//        System.out.println("asize = "+asize);
//        System.out.println("bsize = "+bsize);
        TreeSet<Long> t = new TreeSet<Long>();
        //ProsesSatu pc = new ProsesSatu();
        for (int i = 0; i < asize; i++) {
            t.add(a[i]);
        }
        for (int i = 0; i < bsize; i++) {
            t.add(b[i]);
        }
        return t.size();
    }

    static int doCompare1(long[] a, long[] b) {
        int i = 0;
        int j = 0;
        int score = 0;
        while (a[i] != 0) {
            j = 0;
            while (b[j] != 0) {
                if (a[i] == b[j]) {
                    score += 1;
                    //System.out.println(a[j]);
                }
                j++;

            }
            i++;
        }
        return score;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonHitung;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonCek;
    private javax.swing.JButton jButtonHelp;
    private javax.swing.JButton jButtonHistory;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCek;
    private javax.swing.JPanel jPanelHelp;
    private javax.swing.JPanel jPanelHistory;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    // End of variables declaration//GEN-END:variables
}
